USE MASTER
ALTER DATABASE Dem04DB SET SINGLE_USER WITH ROLLBACK IMMEDIATE
DROP DATABASE IF EXISTS Dem04DB
CREATE DATABASE Dem04DB

USE Dem04DB

CREATE TABLE Clients(
	ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	_Name NVARCHAR(50) NOT NULL,
	_Surname NVARCHAR(50) NOT NULL,
	Number NVARCHAR(10) NOT NULL
)
CREATE TABLE Roles(
	ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	ROLENAME NVARCHAR(50) NOT NULL
)
CREATE TABLE Workers(
	ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	_Name NVARCHAR(50) NOT NULL,
	_Surname NVARCHAR(50) NOT NULL,
	Number NVARCHAR(10) NOT NULL,
	_Role INT REFERENCES ROLES(ID),
)
CREATE TABLE Requests(
	ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	DateOfAccept DATETIME NOT NULL,
	DateOfWorkStart DATETIME,
	RequestDescription NVARCHAR(400),
	RequestState NVARCHAR(15) NOT NULL,
	Client INT REFERENCES Clients(ID),
	Worker INT REFERENCES Workers(ID),
	RequestPriority INT NOT NULL,
)
CREATE TABLE Equipment(
	ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	_Type NVARCHAR(50),
	SerialNumber NVARCHAR(100)
)
CREATE TABLE EquipmentForRequest(
	RequestID INT REFERENCES Requests(ID),
	EquipmentID INT REFERENCES Equipment(ID),
	PRIMARY KEY(RequestID,EquipmentID)
)
